spring:
  application:
    name: earlybird
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: earlybirdteam2024
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  auth:
    apple:
      p8-file: key/AuthKey_FH4V72Y38Q.p8
      client-id: com.earlybirdteam2024.early-bird
fcm:
  service-account-file: key/firebase_admin_sdk_private_key.json
  project-id: ${FCM_PROJECT_ID}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}