[SERVICE]
    Flush 1
    Log_Level info

[OUTPUT]
    Name loki
    Match *
    Url https://earlybirdteam.com:56789
    Labels job=ecs_fargate

[OUTPUT]
    Name s3
    Match *
    bucket earlybird-spring-log
    region ap-northeast-2
    store_dir /tmp/fluent-bit/s3